#!/bin/sh
#
# Test for the Site Build feature (prompts/features/01-site-build.md).
# The build script runs against a temporary directory so that generated
# output never lands in the repository tree.
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
BUILD_SCRIPT="$REPO_ROOT/scripts/site-build.sh"

if grep -q '<html>' "$BUILD_SCRIPT"; then
    echo '01-site-build: build script embeds HTML structure' >&2
    exit 1
fi

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT HUP INT TERM

mkdir -p "$TMP_DIR/in"
printf '%s\n' 'Hello from the site-build test.' > "$TMP_DIR/in/hello.txt"
cp "$REPO_ROOT/site.in/template.html" "$TMP_DIR/in/template.html"

sh "$BUILD_SCRIPT" "$TMP_DIR/in" "$TMP_DIR/out" >/dev/null

OUTPUT_FILE="$TMP_DIR/out/hello.html"

if [ ! -f "$OUTPUT_FILE" ]; then
    echo "01-site-build: missing output file: $OUTPUT_FILE" >&2
    exit 1
fi

grep -q '<!DOCTYPE html>' "$OUTPUT_FILE" || {
    echo '01-site-build: output is missing the doctype' >&2
    exit 1
}

grep -q '<title>hello</title>' "$OUTPUT_FILE" || {
    echo '01-site-build: output is missing the title' >&2
    exit 1
}

grep -q 'Hello from the site-build test.' "$OUTPUT_FILE" || {
    echo '01-site-build: output is missing the input content' >&2
    exit 1
}

grep -q 'generated by scripts/site-build.sh' "$OUTPUT_FILE" || {
    echo '01-site-build: output is missing the generated-file marker' >&2
    exit 1
}

echo '01-site-build: ok'
exit 0
