#!/bin/sh
#
# Test for the Site Build feature (prompts/features/01-site-build.md).
# The build script runs against a temporary directory so that generated
# output never lands in the repository tree.
set -eu

DIRECTORY_SCRIPT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPOSITORY_ROOT=$(CDPATH= cd -- "$DIRECTORY_SCRIPT/.." && pwd)
SCRIPT_BUILD="$REPOSITORY_ROOT/scripts/site-build.sh"

if grep -q '<html>' "$SCRIPT_BUILD"; then
    echo '01-site-build: build script embeds HTML structure' >&2
    exit 1
fi

DIRECTORY_TEMPORARY=$(mktemp -d)
trap 'rm -rf "$DIRECTORY_TEMPORARY"' EXIT HUP INT TERM

mkdir -p "$DIRECTORY_TEMPORARY/in"
printf '%s\n' 'Hello from the site-build test.' > "$DIRECTORY_TEMPORARY/in/hello.txt"
printf '%s\n' 'Fetched __FETCHED__ on __BRANCH__; unset is __MISSING__.' > "$DIRECTORY_TEMPORARY/in/dashboard.txt"
cp "$REPOSITORY_ROOT/site.in/template.html" "$DIRECTORY_TEMPORARY/in/template.html"

printf '%s\n' 'FETCHED=2026-09-24' 'BRANCH=main' > "$DIRECTORY_TEMPORARY/state.txt"

# Set SITE_STATE_FILE explicitly so the test never reads a real state file.
SITE_STATE_FILE="$DIRECTORY_TEMPORARY/state.txt" \
    sh "$SCRIPT_BUILD" "$DIRECTORY_TEMPORARY/in" "$DIRECTORY_TEMPORARY/out" >/dev/null

FILE_OUTPUT="$DIRECTORY_TEMPORARY/out/hello.html"
FILE_DASHBOARD="$DIRECTORY_TEMPORARY/out/dashboard.html"

for file_check in "$FILE_OUTPUT" "$FILE_DASHBOARD"; do
    if [ ! -f "$file_check" ]; then
        echo "01-site-build: missing output file: $file_check" >&2
        exit 1
    fi
done

grep -q '<!DOCTYPE html>' "$FILE_OUTPUT" || {
    echo '01-site-build: output is missing the doctype' >&2
    exit 1
}

grep -q '<title>Hello</title>' "$FILE_OUTPUT" || {
    echo '01-site-build: output is missing the title' >&2
    exit 1
}

grep -q 'Hello from the site-build test.' "$FILE_OUTPUT" || {
    echo '01-site-build: output is missing the input content' >&2
    exit 1
}

grep -q 'generated by scripts/site-build.sh' "$FILE_OUTPUT" || {
    echo '01-site-build: output is missing the generated-file marker' >&2
    exit 1
}

# Live state is substituted from the state file; an unset key renders as
# "unavailable"; no placeholder survives.
grep -q 'Fetched 2026-09-24 on main; unset is unavailable.' "$FILE_DASHBOARD" || {
    echo '01-site-build: live-state substitution is wrong' >&2
    exit 1
}

if grep -q '__[A-Z0-9_]*__' "$FILE_DASHBOARD"; then
    echo '01-site-build: a placeholder survived substitution' >&2
    exit 1
fi

# Without a state file the build stays portable: every key is "unavailable".
SITE_STATE_FILE="$DIRECTORY_TEMPORARY/absent.txt" \
    sh "$SCRIPT_BUILD" "$DIRECTORY_TEMPORARY/in" "$DIRECTORY_TEMPORARY/out-portable" >/dev/null

grep -q 'Fetched unavailable on unavailable; unset is unavailable.' \
    "$DIRECTORY_TEMPORARY/out-portable/dashboard.html" || {
    echo '01-site-build: the portable fallback is wrong' >&2
    exit 1
}

echo '01-site-build: ok'
exit 0
