#!/bin/sh
#
# Test for the Site Build feature (prompts/features/01-site-build.md).
# The build script runs against a temporary directory so that generated
# output never lands in the repository tree.
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/.." && pwd)
build_script="$repo_root/scripts/site-build.sh"

tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT HUP INT TERM

mkdir -p "$tmp_dir/in"
printf '%s\n' 'Hello from the site-build test.' > "$tmp_dir/in/hello.txt"

sh "$build_script" "$tmp_dir/in" "$tmp_dir/out" >/dev/null

output_file="$tmp_dir/out/hello.html"

if [ ! -f "$output_file" ]; then
    echo "01-site-build: missing output file: $output_file" >&2
    exit 1
fi

grep -q '<!DOCTYPE html>' "$output_file" || {
    echo '01-site-build: output is missing the doctype' >&2
    exit 1
}

grep -q '<title>hello</title>' "$output_file" || {
    echo '01-site-build: output is missing the title' >&2
    exit 1
}

grep -q 'Hello from the site-build test.' "$output_file" || {
    echo '01-site-build: output is missing the input content' >&2
    exit 1
}

grep -q 'generated by scripts/site-build.sh' "$output_file" || {
    echo '01-site-build: output is missing the generated-file marker' >&2
    exit 1
}

echo '01-site-build: ok'
exit 0
