#!/bin/sh
#
# build-site.sh: generate the static site in site.out/ from site.in/.
#
# Feature: prompts/features/01-build-site.md
#
# Usage: build-site.sh [INPUT_DIR] [OUTPUT_DIR]
#
# The default INPUT_DIR is site.in/ and the default OUTPUT_DIR is site.out/,
# both relative to the repository root.
# Every site.in/*.txt input file is converted to site.out/<name>.html.
#
# Generated output is stamped with a generated-file marker and must not be
# edited manually.
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/.." && pwd)

input_dir=${1:-"$repo_root/site.in"}
output_dir=${2:-"$repo_root/site.out"}

if [ ! -d "$input_dir" ]; then
    echo "build-site: input directory not found: $input_dir" >&2
    exit 1
fi

mkdir -p "$output_dir"

built_count=0
for input_file in "$input_dir"/*.txt; do
    if [ ! -f "$input_file" ]; then
        continue
    fi
    base_name=$(basename "$input_file" .txt)
    output_file="$output_dir/$base_name.html"
    {
        echo '<!-- generated by scripts/build-site.sh; do not edit manually -->'
        echo '<!DOCTYPE html>'
        echo '<html>'
        echo '<head>'
        echo '  <meta charset="utf-8">'
        echo "  <title>$base_name</title>"
        echo '</head>'
        echo '<body>'
        echo '  <main>'
        sed 's/^/    /' "$input_file"
        echo '  </main>'
        echo '</body>'
        echo '</html>'
    } > "$output_file"
    built_count=$((built_count + 1))
done

echo "build-site: built $built_count page(s) into $output_dir"
exit 0
