#!/bin/sh
#
# site-build.sh: generate the static site in site.out/ from site.in/.
#
# Feature: prompts/features/01-site-build.md
#
# Usage: site-build.sh [INPUT_DIR] [OUTPUT_DIR]
#
# The default INPUT_DIR is site.in/ and the default OUTPUT_DIR is site.out/,
# both relative to the repository root.
# Every site.in/*.txt input file is converted to site.out/<name>.html.
# The HTML page structure lives in site.in/template.html, not in this script.
# The template marker <!-- SITE-CONTENT --> marks where page content is inserted.
#
# Generated output is stamped with a generated-file marker and must not be
# edited manually.
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)

INPUT_DIR=${1:-"$REPO_ROOT/site.in"}
OUTPUT_DIR=${2:-"$REPO_ROOT/site.out"}
TEMPLATE="$INPUT_DIR/template.html"
MARKER='<!-- SITE-CONTENT -->'

if [ ! -d "$INPUT_DIR" ]; then
    echo "site-build: input directory not found: $INPUT_DIR" >&2
    exit 1
fi

if [ ! -f "$TEMPLATE" ]; then
    echo "site-build: template not found: $TEMPLATE" >&2
    exit 1
fi

if ! grep -q "$MARKER" "$TEMPLATE"; then
    echo "site-build: template is missing the marker line: $MARKER" >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

built_count=0
for input_file in "$INPUT_DIR"/*.txt; do
    if [ ! -f "$input_file" ]; then
        continue
    fi
    base_name=$(basename "$input_file" .txt)
    escaped_title=$(printf '%s' "$base_name" | sed 's/\\/\\\\/g; s/&/\\&/g; s|/|\\/|g')
    output_file="$OUTPUT_DIR/$base_name.html"
    {
        echo '<!-- generated by scripts/site-build.sh; do not edit manually -->'
        sed "s/__TITLE__/$escaped_title/g" "$TEMPLATE" | sed "/$MARKER/q" | sed '$d'
        sed 's/^/    /' "$input_file"
        sed -n "/$MARKER/,\$p" "$TEMPLATE" | sed '1d'
    } > "$output_file"
    built_count=$((built_count + 1))
done

echo "site-build: built $built_count page(s) into $OUTPUT_DIR"
exit 0
