#!/bin/sh
#
# site-condense.sh: generate the condensed pages for the project site.
#
# Convention: the homelab project's documents/09-project-pages-conventions.md
# (standard page set). Generates site.out/todo.html, site.out/prompts.html,
# and site.out/documents.html from THIS project's own TODO.md, prompts/, and
# documents/ at build time, so the pages stay current without hand-editing.
#
#   todo.html       - open items (completed items summarized as a count).
#                     Handles both `* [ ]` and `- [ ]` bullet styles.
#   prompts.html    - file map of prompts/ (path + first heading)
#   documents.html  - file map of documents/ (path + first heading)
#
# Condensation is index/summary, never full contents.
# Reuses site.in/template.html (marker <!-- SITE-CONTENT -->, __TITLE__).
#
# Usage: site-condense.sh
set -eu

DIRECTORY_SCRIPT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPOSITORY_ROOT=$(CDPATH= cd -- "$DIRECTORY_SCRIPT/.." && pwd)
DIRECTORY_INPUT="$REPOSITORY_ROOT/site.in"
DIRECTORY_OUTPUT="$REPOSITORY_ROOT/site.out"
FILE_TEMPLATE="$DIRECTORY_INPUT/template.html"
COMMENT_MARKER='<!-- SITE-CONTENT -->'

mkdir -p "$DIRECTORY_OUTPUT"

# html_escape: escape & < > for safe inclusion in HTML text.
html_escape() {
    sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g'
}

# page: wrap the given content file in the site template.
# Usage: page TITLE CONTENT_FILE OUTPUT_FILE
page() {
    title=$1
    content=$2
    output=$3
    title_escaped=$(printf '%s' "$title" | sed 's/\\/\\\\/g; s/&/\\&/g; s|/|\\/|g')
    {
        echo '<!-- generated by scripts/site-condense.sh; do not edit manually -->'
        sed "s/__TITLE__/$title_escaped/g" "$FILE_TEMPLATE" | sed "/$COMMENT_MARKER/q" | sed '$d'
        sed 's/^/    /' "$content"
        sed -n "/$COMMENT_MARKER/,\$p" "$FILE_TEMPLATE" | sed '1d'
    } > "$output"
}

# map_md: emit a file map of a markdown directory into an HTML page.
# Usage: map_md TITLE DIR OUTPUT_FILE
map_md() {
    title=$1
    dir=$2
    output=$3
    tmp_map=$(mktemp)
    {
        echo '<ul>'
        if [ -d "$dir" ]; then
            for f in $(find "$dir" -name '*.md' -type f | sort); do
                rel=${f#"$REPOSITORY_ROOT"/}
                heading=$(sed -n 's/^#\{1,\}[[:space:]]*//p' "$f" | head -1)
                [ -n "$heading" ] || heading='(no heading)'
                printf '  <li><code>%s</code> — %s</li>\n' \
                    "$(printf '%s' "$rel" | html_escape)" \
                    "$(printf '%s' "$heading" | html_escape)"
            done
        else
            echo '  <li>no directory</li>'
        fi
        echo '</ul>'
    } > "$tmp_map"
    page "$title" "$tmp_map" "$output"
    rm -f "$tmp_map"
}

FILE_TODO="$REPOSITORY_ROOT/TODO.md"

# --- todo.html ---------------------------------------------------------------
tmp_todo=$(mktemp)
if [ -f "$FILE_TODO" ]; then
    open_items=$(awk '
        /^[*\-] \[ \]/ {
            if (item) print item_text
            item = 1
            line = $0
            sub(/^[*\-] \[ \] */, "", line)
            item_text = line
            next
        }
        item && /^[[:space:]]/ {
            line = $0
            sub(/^[[:space:]]+/, "", line)
            item_text = item_text " " line
            next
        }
        item { print item_text; item = 0 }
        END { if (item) print item_text }
    ' "$FILE_TODO")
    open_count=$(printf '%s\n' "$open_items" | grep -c . || true)
    done_count=$(grep -cE '^[*\-] \[x\]' "$FILE_TODO" || true)
else
    open_items=""
    open_count=0
    done_count=0
fi

{
    echo '<h1>Todo</h1>'
    echo "<p>Condensed from <code>TODO.md</code> at build time: $open_count open item(s), $done_count completed.</p>"
    if [ -n "$open_items" ]; then
        echo '<ul>'
        printf '%s\n' "$open_items" | while IFS= read -r item; do
            printf '  <li>%s</li>\n' "$(printf '%s' "$item" | html_escape)"
        done
        echo '</ul>'
    else
        echo '<p>No open items.</p>'
    fi
} > "$tmp_todo"
page 'Todo' "$tmp_todo" "$DIRECTORY_OUTPUT/todo.html"
rm -f "$tmp_todo"

# --- prompts.html / documents.html -------------------------------------------
map_md 'Prompts' "$REPOSITORY_ROOT/prompts" "$DIRECTORY_OUTPUT/prompts.html"
map_md 'Documents' "$REPOSITORY_ROOT/documents" "$DIRECTORY_OUTPUT/documents.html"

echo "site-condense: built todo.html, prompts.html, documents.html into $DIRECTORY_OUTPUT"
exit 0
