#!/bin/sh
#
# site-build.sh: generate the static site in site.out/ from site.in/.
#
# Feature: prompts/features/01-site-build.md
#
# Usage: site-build.sh [DIRECTORY_INPUT] [DIRECTORY_OUTPUT]
#
# The default DIRECTORY_INPUT is site.in/ and the default DIRECTORY_OUTPUT is
# site.out/, both relative to the repository root.
# Every site.in/*.txt input file is converted to site.out/<name>.html.
# The HTML page structure lives in site.in/template.html, not in this script.
# The template marker <!-- SITE-CONTENT --> marks where page content is inserted.
#
# Generated output is stamped with a generated-file marker and must not be
# edited manually.
set -eu

DIRECTORY_SCRIPT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPOSITORY_ROOT=$(CDPATH= cd -- "$DIRECTORY_SCRIPT/.." && pwd)

DIRECTORY_INPUT=${1:-"$REPOSITORY_ROOT/site.in"}
DIRECTORY_OUTPUT=${2:-"$REPOSITORY_ROOT/site.out"}
FILE_TEMPLATE="$DIRECTORY_INPUT/template.html"
COMMENT_MARKER='<!-- SITE-CONTENT -->'

if [ ! -d "$DIRECTORY_INPUT" ]; then
    echo "site-build: input directory not found: $DIRECTORY_INPUT" >&2
    exit 1
fi

if [ ! -f "$FILE_TEMPLATE" ]; then
    echo "site-build: template not found: $FILE_TEMPLATE" >&2
    exit 1
fi

if ! grep -q "$COMMENT_MARKER" "$FILE_TEMPLATE"; then
    echo "site-build: template is missing the marker line: $COMMENT_MARKER" >&2
    exit 1
fi

mkdir -p "$DIRECTORY_OUTPUT"

built_count=0
for input_file in "$DIRECTORY_INPUT"/*.txt; do
    if [ ! -f "$input_file" ]; then
        continue
    fi
    base_name=$(basename "$input_file" .txt)
    escaped_title=$(printf '%s' "$base_name" | sed 's/\\/\\\\/g; s/&/\\&/g; s|/|\\/|g')
    output_file="$DIRECTORY_OUTPUT/$base_name.html"
    {
        echo '<!-- generated by scripts/site-build.sh; do not edit manually -->'
        sed "s/__TITLE__/$escaped_title/g" "$FILE_TEMPLATE" | sed "/$COMMENT_MARKER/q" | sed '$d'
        sed 's/^/    /' "$input_file"
        sed -n "/$COMMENT_MARKER/,\$p" "$FILE_TEMPLATE" | sed '1d'
    } > "$output_file"
    built_count=$((built_count + 1))
done

echo "site-build: built $built_count page(s) into $DIRECTORY_OUTPUT"
exit 0
